//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NumbersToWordsClient.CurrencyConversionService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CurrencyConversionService.ICurrencyConversionService")]
    public interface ICurrencyConversionService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICurrencyConversionService/ConvertCurrencyToText", ReplyAction="http://tempuri.org/ICurrencyConversionService/ConvertCurrencyToTextResponse")]
        string ConvertCurrencyToText(decimal value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICurrencyConversionService/ConvertCurrencyToText", ReplyAction="http://tempuri.org/ICurrencyConversionService/ConvertCurrencyToTextResponse")]
        System.Threading.Tasks.Task<string> ConvertCurrencyToTextAsync(decimal value);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICurrencyConversionServiceChannel : NumbersToWordsClient.CurrencyConversionService.ICurrencyConversionService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CurrencyConversionServiceClient : System.ServiceModel.ClientBase<NumbersToWordsClient.CurrencyConversionService.ICurrencyConversionService>, NumbersToWordsClient.CurrencyConversionService.ICurrencyConversionService {
        
        public CurrencyConversionServiceClient() {
        }
        
        public CurrencyConversionServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CurrencyConversionServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CurrencyConversionServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CurrencyConversionServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string ConvertCurrencyToText(decimal value) {
            return base.Channel.ConvertCurrencyToText(value);
        }
        
        public System.Threading.Tasks.Task<string> ConvertCurrencyToTextAsync(decimal value) {
            return base.Channel.ConvertCurrencyToTextAsync(value);
        }
    }
}
